# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache:
  - packages
  - ccache

latex: false

os:
  - linux
  - osx

dist: xenial

r:
  - oldrel
  - release
  - devel
  - 3.5
  - 3.4

matrix:
  fast_finish: true
  allow_failures:
    - r: devel
      os: osx

addons:
  postgresql: "9.6"

before_install:
  - chmod +x ./.travis/install.sh
  - ./.travis/install.sh

r_packages:
  - devtools
  - lazyeval

before_cache:
  - brew cleanup

after_success:
  - dropdb postgis
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  - Rscript -e 'covr::codecov()'
